"""head

Revision ID: 0.1.0-alpha
Revises: 
Create Date: 2017-04-22 17:15:58.780485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0.1.0-alpha'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('billing_dom', sa.Integer(), nullable=False, server_default='28'))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('clients', 'billing_dom')
    # ### end Alembic commands ###
